### PR TITLE
Update engine registration target to app.assets

### PR DESCRIPTION
**Pull request by vijoc**
I had some issues with a setup including `requirejs-rails` and `hamlbars`. I first implemented this change locally in my app, but figured others might benefit from it. I'm not sure why this fixed the issue, but it did.

### CODE REVIEW

**Comment by vijoc** [comment]
Actually I'm still having issues with integrating `handlebars_assets` to my application. The issue is that the AMD modules are rendered in a very wonky way; the return value is a string containing the `define([handlebars], ....` header and everything. Still investigating.

**Comment by AlexRiedler** [comment]
@vijoc I remember for hamlbars prior to v2 there were issues because of registering the same extension (e.g. hamlbars and handlbars_assets gem both would try to grab .hamlbars).

I would recommend configuring the handlebars_assets get (this gem); so that:

```ruby
HandlebarsAssets.Config.configure do |config|
    config.hamlbars_extensions = '.hamlbars_assets'
end
```

that way it will not conflict with hamlbars gem.

**Comment by vijoc** [comment]
Actually I resolved the issue by setting `config.hamlbar_extensions = []`, which of course has the same effect in this case. As I poked around the codebase I found the option `haml_enabled` but it doesn't seem to be used, at least not when deciding whether to use the haml engine or not. Maybe that could be used to tell handlebars_assets not to worry about `.hamlbars` files by default?

**Comment by AlexRiedler** [comment]
@vijoc yup that is the other way to do it :) but basically the same effect.

**Pull request closed without merging**
